add_library(commands_cpp OBJECT ${PROJECT_SOURCE_DIR}/src/commands.cpp)
set_target_properties(
    commands_cpp
    PROPERTIES
    INCLUDE_DIRECTORIES "${QLENS_INCLUDE_DIRS}"
    COMPILE_DEFINITIONS "${QLENS_COMPILE_DEFINITIONS}"
    COMPILE_FLAGS "${QLENS_COMPILE_FLAGS} -O0"
    #LINK_LIBRARIES ${GDP_LIBRARIES}
    LINK_FLAGS "${QLENS_LINKER_FLAGS}"
    LINKER_LANGUAGE CXX
)

add_executable(qlens
    ${QLENS_SOURCES}
)

set_target_properties(
    qlens 
    PROPERTIES
    INCLUDE_DIRECTORIES "${QLENS_INCLUDE_DIRS}"
    COMPILE_DEFINITIONS "${QLENS_COMPILE_DEFINITIONS}"
    COMPILE_FLAGS "${QLENS_COMPILE_FLAGS} -Ofast"
    #LINK_LIBRARIES ${GDP_LIBRARIES}
    LINK_FLAGS "${QLENS_LINKER_FLAGS}"
    RUNTIME_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/bin"
    LINKER_LANGUAGE Fortran
    OUTPUT_NAME "qlens"
)

add_dependencies(qlens commands_cpp)# cmake_cmd)

target_link_libraries(qlens ${QLENS_LIBRARIES})

add_executable(mkdist
    ${MKDIST_SOURCES}
)

set_target_properties(
    mkdist 
    PROPERTIES
    INCLUDE_DIRECTORIES "${QLENS_INCLUDE_DIRS}"
    COMPILE_DEFINITIONS "${QLENS_COMPILE_DEFINITIONS}"
    COMPILE_FLAGS "${QLENS_COMPILE_FLAGS} -Ofast"
    #LINK_LIBRARIES ${GDP_LIBRARIES}
    LINK_FLAGS "${QLENS_LINKER_FLAGS}"
    RUNTIME_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/bin"
    LINKER_LANGUAGE CXX
    OUTPUT_NAME "mkdist"
)

target_link_libraries(mkdist ${QLENS_LIBRARIES})

add_executable(cosmocalc
    ${COSMOCALC_SOURCES}
)

set_target_properties(
    cosmocalc
    PROPERTIES
    INCLUDE_DIRECTORIES "${QLENS_INCLUDE_DIRS}"
    COMPILE_DEFINITIONS "${QLENS_COMPILE_DEFINITIONS}"
    COMPILE_FLAGS "${QLENS_COMPILE_FLAGS} -Ofast"
    #LINK_LIBRARIES ${GDP_LIBRARIES}
    LINK_FLAGS "${QLENS_LINKER_FLAGS}"
    RUNTIME_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/bin"
    LINKER_LANGUAGE Fortran
    OUTPUT_NAME "cosmocalc"
)

target_link_libraries(cosmocalc ${QLENS_LIBRARIES})
